### ISSUE TITLE
OnFirstLoad bug that has no solution

### ISSUE THREAD

**Issue by Nyphur** [NoelStephensUnity/Netcode-For-GameObjects-BootStrap-Pattern#2]
The OnFirstLoad method of BootStrapSceneLoader is a handy little piece of code, it seems that the intention is to ensure the scenes load in Play mode in the editor exactly as they would in a build. Unfortunately there's a fairly serious bug in this method that means it doesn't really achieve this goal and so doesn't work as a generalised solution:

1. If you have the bootstrap scene and another scene open when you click the play button, that second scene never gets unloaded. Even if you explicitly call SceneManager.UnloadSceneAsync on that scene within the OnFirstLoad method, Unity can't unload it.
2. If you don't have the bootstrap scene open in the editor then OnFirstLoad calls SceneManager.LoadScene(0) correctly and all the other active scenes in the editor go away, but Unity still loads and executes all those scenes before removing them. This includes calling Awake on all components, adding things to DontDestroyOnLoad, initialising stuff, throwing exceptions, and loads more things that won't happen in a build.

There doesn't seem to be a solution for this because Unity actually has no way to prevent a scene from loading. Even if you set OnFirstLoad's RuntimeInitializeLoadType to BeforeSceneLoad, there's nothing you can actually do within that method to stop Unity from loading and executing all the existing scenes. The only way to ensure the scenes load the exact same way as in a build is to manually close all scenes except the BootStrap scene before clicking Play every single time.

The only workaround I can think of is to create an Unity Editor script that closes all scenes and then enters play mode.

**Comment by NoelStephensUnity** [comment]
@Nyphur 
That was a good catch (_thank you for pointing that out_) and I fixed it by just loading the bootstrap each time you enter into play mode. When you exit, all of the scenes you had loaded are restored.

**Comment by Nyphur** [comment]
This is great but it's unfortunately only a partial fix. When you enter Play mode in the editor, Unity still goes through a lot of the work of loading and then unloading all currently open scenes before it loads the bootstrap scene. It calls the Awake, OnEnable, OnDisable, and OnDestroy methods on all objects in any open scenes. This is behaviour that doesn't happen in a build, and so can lead to inconsistent behaviour between build and editor.

**Comment by NoelStephensUnity** [comment]
The [code you are referring to is wrapped in the #if UNITY_EDITOR](https://github.com/NoelStephensUnity/Netcode-For-GameObjects-BootStrap-Pattern/blob/61453afcb5e3c22da7f1008f0f525403dcd08285/Assets/Scripts/BootStrapSceneLoader.cs#L67) which is not included in release builds on purpose.

The general idea is that if you have a scene open, other than the bootstrap, it will load the bootstrap automatically for you as opposed to you having to close the scene you are currently working on and open the bootstrap. In reality, that code replicates the same sequence of events that would occur within a release build since the bootstrap scene is the first thing loaded.

Without that in place, there is more of a chance to not take everything into account when working on additional scenes that are loaded during a network session that you wouldn't discover until making a release build and testing that way.

Of course, feel free to fork the repository and make any adjustments that you feel better suits your project's needs and/or development style.

**Comment by Nyphur** [comment]
I understand that the code is only executed in the editor and that its purpose is to replicate the same sequence of events that would occur within a release build, I'm saying that it doesn't achieve that.

Before this code kicks in and loads the bootstrap scene Unity will still load and then unload all scenes that are open in the editor in play mode at runtime. This calls every object's Awake, OnEnable, OnDisable and OnDestroy method, a sequence of events that doesn't occur within a release build and can lead to very different behaviours between editor and build. It's not just a matter of personal development style or project needs, every project will have components using Awake, OnEnable, OnDisable or OnDestroy.

I found two solutions though! The cleanest one was to create an editor script using [InitializeOnLoadAttribute] that sets Unity's built-in playModeStartScene variable in the EditorSceneManager. This bypasses the entire scene loading and unloading process, Unity skips straight to the new scene and doesn't execute the Awake methods etc. This also makes the scene-loading in BootStrapSceneLoader unnecessary, and retains any unsaved scene edits as normal. This is the script:

```
#if UNITY_EDITOR
using UnityEditor;

// Call initialiser on script recompile
[InitializeOnLoadAttribute]
public static class BootstrapSceneEditorReloader
{
    // Set the start scene to the bootstrap scene when the class is initialised
    static BootstrapSceneEditorReloader()
    {
        UnityEditor.SceneManagement.EditorSceneManager.playModeStartScene = AssetDatabase.LoadAssetAtPath<SceneAsset>(UnityEditor.SceneManagement.EditorSceneManager.GetSceneByBuildIndex(0).path);
    }
}
#endif
```

With this method, we can remove the SceneManager.LoadScene(0) call from OnFirstLoad, and it's also not clear that the OnFirstLoad method, the OnFirstSceneLoaded method and CatchEnterPlayMode code needs to exist any more as the Bootstrap scene should not end up loaded multiple times and there should never be a risk of duplicate NetworkManager. This method also seems faster, and it may be just a straight-up cleaner way of achieving the same result.
