### ISSUE TITLE
Redundant bootstrap scene

### ISSUE THREAD

**Issue by Nyphur** [NoelStephensUnity/Netcode-For-GameObjects-BootStrap-Pattern#3]
The project description says that the purpose of the bootstrap scene is to be the only scene loaded in single mode, but there are two such scenes in the project. The base BootStrap scene exists only to immediately load a second bootstrap scene called DefaultActiveScene in single mode and then delete itself. There doesn't really seem to any benefit to doing it this way and it goes against the proposed pattern.

If we merge all of DefaultActiveScene into the BootStrap scene then we can remove BootStrapSceneLoader.cs and the scene loading code from the SceneEntry.SetAsActiveScene method that it calls. That code only exists to load another scene in single mode, which isn't a feature we need to support in this pattern. This also simplifies the project conceptually because we aren't using SceneEntry in two different scene loading mechanisms, only in the additive loading mechanism of NetcodeSceneLoader.cs.

Suggestions:
- Put all of DefaultActiveScene into the BootStrap scene
- Delete BootStrapSceneLoader.cs
- Remove the ScreenManager lines from SceneEntry.SetAsActiveScene
- Call SceneEntry.SetAsActiveScene in NetcodeSceneLoader.Awake, passing in gameObject.scene

Gave this a try and it worked fine, and seemed much more streamlined.

**Comment by NoelStephensUnity** [comment]
Hi @Nyphur! 
Thank you for your feedback and I think I can help clear some things up for you.

> The project description says that the purpose of the bootstrap scene is to be the only scene loaded in single mode, but there are two such scenes in the project.

My guess is you are referring to [this part of the Readme.md file](https://github.com/NoelStephensUnity/Netcode-For-GameObjects-BootStrap-Pattern/blob/55256c7ba673d338c7d322b6ab350391fe15838e/README.md?plain=1#L13). You might have misunderstood that sentence:

_"The "Bootstrap Usage Pattern" involves having one (1) scene, typically set to index 0 of the Build Settings-->Scene in Build list, that is the only scene loaded in single mode for the entire duration of your runtime instance."_

The intention behind this sentence was to convey that the very first scene loaded (index 0) defaults to being loaded in `LoadSceneMode.Single` and that it is the only scene loaded in `LoadSceneMode.Single` throughout the entire project. Please feel free to search the source code for any reference to `LoadSceneMode.Single` or a call to `SceneMannager.LoadScene` where it either doesn't pass in `LoadSceneMode.Additive` or invokes `SceneMannager.LoadScene` without any parameters and does not load the scene index 0.

After the BootStrap scene is loaded, it [loads the "FirstSceneToLoad" additively](https://github.com/NoelStephensUnity/Netcode-For-GameObjects-BootStrap-Pattern/blob/55256c7ba673d338c7d322b6ab350391fe15838e/Assets/Scripts/BootStrapSceneLoader.cs#L47) and then from that point forward handles all scene loading additively.


> The base BootStrap scene exists only to immediately load a second bootstrap scene called DefaultActiveScene in single mode and then delete itself.

This is actually part of the pattern and the DefaultActiveScene does not always have to persist either (although you are right that it does continually persist after is has been loaded for the example I provided). Using this base set of components, you could configure it load some other scene and make that scene the default active scene. 

_It is an example of the usage pattern and is meant to be a starting point that you can modify to behave the way you want it to behave._

### There are a few key concepts here:

**BootStrap Scene:** This is used to get the NetworkManger into the DDOL and then to load some other scene and make that scene the active scene. The "BootStrap" scene is not meant to persist throughout the entire application life cycle... it is meant to be the initial first loading sequence where you can place anything that you want to persist into the DDOL or the like. You might opt to load a few splash screens between the BootStrap and the DefaultActiveScene.

**Default Active Scene:** This is where all newly instantiated GameObjects will be created. If you want newly instantiated GameObjects to be located in a different scene, then you have to migrate them into that scene after the GameObject is instanted (i.e. from the "Default" active scene into "some other scene).

Feel free to make any form of modifications that you feel fits your project's needs as it is only an example of the usage pattern _(i.e. 1 scene is loaded in single mode and everything from that point forward is loaded additively)_.

**Comment by NoelStephensUnity** [comment]
@Nyphur 
I am gong to close this issue out since:

- The readme does indeed describe what is happening and there is only 1 scene loaded in single mode.
- The suggested changes are something that can be easily modified/adjusted (and since this is only intended as a starting point).
