### ISSUE TITLE
BootStrapSceneLoader custom editor hides FirstSceneToLoad variable

### ISSUE THREAD

**Issue by Nyphur** [NoelStephensUnity/Netcode-For-GameObjects-BootStrap-Pattern#6]
The recent change to BootStrapSceneLoader.cs added a custom editor to hide the resolution options if you untick Set Resolution. This Editor UI doesn't expose the FirstSceneToLoad variable.

**Comment by NoelStephensUnity** [comment]
Good catch!
Thank you for helping with this project.  
🥇
